### ISSUE TITLE
duplicates in output

### ISSUE THREAD

**Issue by jpopelka** [pkajaba/maven-index-checker#3]
For example:
$ java -jar maven-index-checker.jar -r 10-20
[{"groupId":"org.neo4j","artifactId":"neo4j-kernel","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-kernel","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-kernel","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-kernel","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-kernel","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-kernel","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-lucene-index","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-lucene-index","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-lucene-index","version":"1.7.M03"},{"groupId":"org.neo4j","artifactId":"neo4j-lucene-index","version":"1.7.M03"}]

Do you think removing the duplicates would be confusing for user ? (In a sense that the tool would return 2 entries, while 10-20 was requested)
Or is it a bug ?

**Comment by pkajaba** [comment]
I am not 100% sure whether it is bug or not. But if it is not I would add option to filter duplicates rather than just filtering.

**Comment by pkajaba** [comment]
So it is a bug. It outputs javadocs, tests and sources jars. I will correct it

**Comment by pkajaba** [comment]
It's fixed now

**Comment by jpopelka** [comment]
Thanks !
